[package]
name = "ic_cose_chain_key"
version = "0.11.0"
edition.workspace = true
description = "ICP chain-key calls, cost estimates and public-key derivation for dMsg canisters"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ldclabs/ic-panda/tree/main/src/ic_cose_chain_key"
publish = false

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-dummy-getrandom-for-wasm.workspace = true
ic-cdk-management-canister.workspace = true
ic-ed25519.workspace = true
ic-secp256k1.workspace = true
serde.workspace = true
serde_bytes.workspace = true
