[package]
name = "dmsg_test_sns"
version = "0.1.0"
edition.workspace = true
publish = false
[lib]
crate-type = ["cdylib"]
[dependencies]
candid.workspace = true
serde = { workspace = true, features = ["derive"] }
ic-cdk.workspace = true
ic-stable-structures.workspace = true
dmsg_runtime = { path = "../../src/dmsg_runtime" }
lib_dummy_getrandom = { path = "../../src/lib_dummy_getrandom" }
