[package]
name = "dmsg_test_ledger"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]
test = false

[dependencies]
dmsg_protocol = { path = "../../src/dmsg_protocol" }
dmsg_runtime = { path = "../../src/dmsg_runtime" }
ic-stable-structures.workspace = true
candid.workspace = true
ic-cdk.workspace = true
icrc-ledger-types.workspace = true
serde.workspace = true
num-traits.workspace = true
lib_dummy_getrandom = { path = "../../src/lib_dummy_getrandom" }
