# Load the environment variables
source "$(pwd)"/proposals/env.sh

quill sns make-proposal --canister-ids-file ./sns_canister_ids.json --pem-file $PROPOSAL_PEM_FILE $PROPOSAL_NEURON_ID --proposal "(
    record {
        title = \"Proposal for Marketing Campaign Partnership between CryptoEights and ICPanda DAO\";
        url = \"https://twitter.com/CryptoEights\";
        summary = \"CryptoEights generously organized [ICPanda DAO's first AMA event](https://twitter.com/CryptoEights/status/1774798813695488247) for free, that helps us greatly!\nBelieving in CryptoEights's professionalism and influence, we plan to continue a 3-month marketing partnership with them. For this, we will pay 140 ICP from the treasury to CryptoEights.\";
        action = opt variant {
            Motion = record {
                motion_text = \"Below is the partnership agreement drafted by Pebriansyah, a co-founder of CryptoEights.\n\nDear ICPanda DAO Team,\n\nWe are thrilled to present this proposal for a comprehensive marketing campaign partnership between CryptoEights and ICPanda DAO. Our goal is to elevate the visibility, engagement, and community involvement of ICPanda DAO through a strategic and targeted approach over the course of three months.\n\n1. Partnership between CryptoEights x ICPanda DAO\nWe propose a close collaboration between CryptoEights and ICPanda DAO, aimed at fostering mutual growth and success within the crypto community.\n\n2. Daily Shilling for 3 Month Duration:\nCryptoEights will engage in daily shilling activities across various platforms to create consistent buzz and interest around ICPanda DAO for a duration of three months.\n\n3. Weekly In-Depth Overview and Review:\nWe will provide weekly in-depth technical analysis or fundamental analysis of ICPanda DAO, adding significant value to the project and ensuring that the community remains informed and educated about its progress.\n\n4. Mentioning ICPanda's Latest Updates:\nCryptoEights will regularly feature ICPanda DAO's latest updates and developments in our Web3 Wizards Space, amplifying its reach and impact within the broader crypto ecosystem.\n\n5. Quote Important Tweets:\nWe will curate and quote important tweets from ICPanda DAO's official account, maximizing their visibility and engagement across our platforms.\n\n6. Brand Positioning with Purpose:\nCryptoEights will strategically position ICPanda DAO to garner positive public and community opinion, thereby enhancing awareness and fostering a favorable perception of the project.\n\n7. Collaboration Facilitation:\nWe will facilitate connections between ICPanda DAO and other projects to explore potential collaborations, leveraging our network and expertise to create mutually beneficial partnerships.\n\nTerm and Service Fee:\nThis proposal outlines a three-month partnership with the option to extend based on the achieved results and KPIs. The service fee for this comprehensive marketing campaign is set at 140 ICP.\n\nICP Address for Payment: mdpkg-77n55-ialpr-4awyj-tzmf6-fhgco-6fbu5-k7itz-p4r7h-fqqdt-mqe\n\nMonthly Reporting:\nCryptoEights is committed to providing detailed monthly reports to ICPanda DAO, including metrics such as impressions, engagement, and overall impact, ensuring transparency and accountability throughout the partnership.\n\nWe believe that this partnership will significantly contribute to the growth and success of ICPanda DAO, and we are excited about the opportunity to work closely with your team. Should you have any questions or require further information, please do not hesitate to reach out.\n\nThank you for considering our proposal. We look forward to the possibility of collaborating with you.\n\nWarm regards,\n\nPebriansyah\nCo-Founder\nCryptoEights\n\";
            }
        };
    }
)" > proposal-message.json

# quill send proposal-message.json