import { validateAppAction } from "./action.ts";
import type {
  AppAction,
  AuthenticationRequest,
  CheckoutRequest,
} from "./contracts.ts";
import { DmsgError, ensure } from "./cose-errors.ts";
import {
  base64,
  canonical,
  digest,
  equalBytes,
  hex,
  sha256,
  unbase64,
  unhex,
  utf8,
} from "./encoding.ts";
import {
  EXTENSION_PROTOCOL,
  validateIdentifier,
  validateShape,
} from "./validation.ts";

export { DmsgError } from "./cose-errors.ts";
export { base64, hex, unbase64, unhex } from "./encoding.ts";

export interface BrowserSession {
  publicKeyDer: Uint8Array;
  sign(message: Uint8Array): Promise<Uint8Array>;
}
export interface BrowserCommand {
  method:
    | "authenticate"
    | "signDocument"
    | "signAction"
    | "checkout"
    | "getOperation"
    | "openOperation"
    | "cancelOperation"
    | "acknowledge";
  appId: string;
  operationId: string;
  publicKey: string;
  payload: string | null;
  resultDigest: string | null;
}
export interface BrowserSource {
  origin: string;
  documentId: string;
  tabId: number;
  frameId: number;
}
export type OperationState =
  | "awaiting_user"
  | "authorized"
  | "execution_unknown"
  | "signed"
  | "returned"
  | "rejected"
  | "cancelled"
  | "expired"
  | "failed"
  | "result_expired";
export interface BrowserOperation {
  operationId: string;
  kind: "authentication" | "document" | "action" | "checkout";
  state: OperationState;
  requiresUnlock?: boolean;
  result?: {
    proof?: string;
    artifact?: unknown;
    receipt?: unknown;
    keyDescriptorCbor?: string;
    executionCertificateCbor?: string;
    executionId?: string;
    [key: string]: unknown;
  };
  resultDigest?: string;
}

// Methods that create an operation carry its payload.
const CREATE_METHODS: string[] = [
  "authenticate",
  "signDocument",
  "signAction",
  "checkout",
];
const METHODS = [
  ...CREATE_METHODS,
  "getOperation",
  "openOperation",
  "cancelOperation",
  "acknowledge",
];
const DIGEST = /^[0-9a-f]{64}$/;

export function parseBrowserCommand(value: unknown): BrowserCommand {
  ensure(
    value && typeof value === "object" && !Array.isArray(value),
    "INVALID_INPUT",
  );
  const c = value as BrowserCommand;
  ensure(
    Object.keys(c).sort().join(",") ===
      "appId,method,operationId,payload,publicKey,resultDigest",
    "INVALID_INPUT",
  );
  ensure(METHODS.includes(c.method), "UNSUPPORTED_PROTOCOL");
  validateIdentifier(c.appId);
  ensure(
    typeof c.operationId === "string" &&
      DIGEST.test(c.operationId) &&
      !/^0+$/.test(c.operationId),
    "INVALID_INPUT",
  );
  ensure(unbase64(c.publicKey, 128).length === 91, "INVALID_INPUT");
  const create = CREATE_METHODS.includes(c.method);
  ensure(
    create ? typeof c.payload === "string" : c.payload === null,
    "INVALID_INPUT",
  );
  if (create) unbase64(c.payload!);
  ensure(
    c.method === "acknowledge"
      ? typeof c.resultDigest === "string" && DIGEST.test(c.resultDigest)
      : c.resultDigest === null,
    "INVALID_INPUT",
  );
  return structuredClone(c);
}

/** Nonce is generated by the extension for this connection and consumed once. */
export function browserProofMessage(
  command: BrowserCommand,
  nonce: string,
  source: Pick<BrowserSource, "origin" | "documentId">,
): Uint8Array {
  ensure(
    typeof nonce === "string" &&
      DIGEST.test(nonce) &&
      typeof source.documentId === "string" &&
      source.documentId.length > 0 &&
      source.documentId.length <= 256,
    "INVALID_INPUT",
  );
  return digest("dmsg/browser-proof/v1", [
    EXTENSION_PROTOCOL,
    unhex(nonce),
    source.origin,
    source.documentId,
    command,
  ]);
}

export async function verifyBrowserProof(
  command: BrowserCommand,
  nonce: string,
  source: BrowserSource,
  signature: string,
): Promise<void> {
  const sig = unbase64(signature, 64);
  ensure(sig.length === 64, "INVALID_INPUT");
  const key = await crypto.subtle.importKey(
    "spki",
    unbase64(command.publicKey, 128),
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["verify"],
  );
  ensure(
    await crypto.subtle.verify(
      { name: "ECDSA", hash: "SHA-256" },
      key,
      sig,
      Uint8Array.from(browserProofMessage(command, nonce, source)),
    ),
    "FORBIDDEN",
  );
}

/** Source document is mutable only after a fresh proof from this immutable key. */
export function browserOperationDigest(
  command: BrowserCommand,
  origin: string,
): Uint8Array {
  ensure(CREATE_METHODS.includes(command.method), "INVALID_INPUT");
  return digest("dmsg/browser-operation/v1", [
    origin,
    command.appId,
    command.operationId,
    command.method,
    unbase64(command.publicKey),
    unbase64(command.payload!),
  ]);
}

export interface BrowserPort {
  postMessage(value: unknown): void;
  disconnect(): void;
  onMessage: { addListener(fn: (value: any) => void): void };
  onDisconnect: { addListener(fn: () => void): void };
}

/** The session key stays with the product. No dMsg identity or wallet delegation is exported. */
export function connectDmsg(options: {
  extensionId: string;
  appId: string;
  session: BrowserSession;
  origin?: string;
  connect?: (id: string, options: { name: string }) => BrowserPort;
}) {
  ensure(/^[a-p]{32}$/.test(options.extensionId), "INVALID_EXTENSION");
  validateIdentifier(options.appId);
  const origin = options.origin ?? globalThis.location?.origin;
  ensure(origin && origin !== "null", "INVALID_ORIGIN");
  const connect =
    options.connect ??
    (globalThis as any).chrome?.runtime?.connect?.bind(
      (globalThis as any).chrome.runtime,
    );
  ensure(connect, "EXTENSION_UNAVAILABLE");
  const port: BrowserPort = connect(options.extensionId, {
    name: EXTENSION_PROTOCOL,
  });
  const pending = new Map<
    string,
    {
      command: BrowserCommand | undefined;
      resolve: (v: any) => void;
      reject: (e: Error) => void;
      timer: ReturnType<typeof setTimeout>;
    }
  >();
  let closed = false;
  const finish = (id: string, value: unknown, error?: Error) => {
    const p = pending.get(id);
    if (!p) return;
    clearTimeout(p.timer);
    pending.delete(id);
    error ? p.reject(error) : p.resolve(value);
  };
  // Chrome reports onDisconnect only to the other end; a local disconnect closes here.
  const close = () => {
    closed = true;
    for (const id of pending.keys())
      finish(id, null, new DmsgError("DISCONNECTED"));
  };
  port.onMessage.addListener((message) => {
    if (
      message?.method === "source.challenge" &&
      typeof message.nonce === "string" &&
      DIGEST.test(message.nonce)
    ) {
      port.postMessage({ method: "source.reply", nonce: message.nonce });
      return;
    }
    const p = pending.get(message?.requestId);
    if (!p || message.protocol !== EXTENSION_PROTOCOL) return;
    if (message.type === "challenge") {
      if (
        !p.command ||
        message.origin !== origin ||
        typeof message.documentId !== "string"
      ) {
        finish(message.requestId, null, new DmsgError("SOURCE_MISMATCH"));
        return;
      }
      void (async () => {
        const proof = await options.session.sign(
          browserProofMessage(p.command!, message.nonce, message),
        );
        if (!closed && pending.get(message.requestId) === p)
          port.postMessage({
            protocol: EXTENSION_PROTOCOL,
            requestId: message.requestId,
            type: "proof",
            signature: base64(proof),
          });
      })().catch((e) => finish(message.requestId, null, e));
    } else if (message.type === "result") {
      finish(
        message.requestId,
        message.value,
        message.ok ? undefined : new DmsgError(message.error || "UNAVAILABLE"),
      );
    }
  });
  port.onDisconnect.addListener(close);
  function send(command?: BrowserCommand): Promise<any> {
    if (closed) return Promise.reject(new DmsgError("DISCONNECTED"));
    if (pending.size >= 16)
      return Promise.reject(new DmsgError("QUOTA_EXCEEDED"));
    const id = hex(crypto.getRandomValues(new Uint8Array(32)));
    return new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => finish(id, null, new DmsgError("TRANSPORT_TIMEOUT")),
        30_000,
      );
      pending.set(id, { command, resolve, reject, timer });
      try {
        port.postMessage({
          protocol: EXTENSION_PROTOCOL,
          requestId: id,
          type: command ? "request" : "capabilities",
          ...(command ? { command } : {}),
        });
      } catch (e) {
        finish(id, null, e as Error);
      }
    });
  }
  async function command(
    method: BrowserCommand["method"],
    operationId: string,
    payload: string | null = null,
    resultDigest: string | null = null,
  ): Promise<BrowserOperation> {
    return send(
      parseBrowserCommand({
        method,
        appId: options.appId,
        operationId,
        publicKey: base64(options.session.publicKeyDer),
        payload,
        resultDigest,
      }),
    );
  }
  // Every method reports failures as a rejected promise.
  return {
    capabilities: (): Promise<{ protocol: string; methods: string[] }> =>
      send(),
    authenticate: async (
      request: AuthenticationRequest,
    ): Promise<BrowserOperation> => {
      validateShape("AuthenticationRequest", request);
      ensure(
        request.app_id === options.appId &&
          request.origin === origin &&
          equalBytes(
            request.session_key_hash,
            sha256(options.session.publicKeyDer),
          ),
        "REQUEST_BINDING",
      );
      return command(
        "authenticate",
        hex(request.operation_id),
        base64(canonical(request)),
      );
    },
    signDocument: async (
      operationId: string,
      documentRequest: unknown,
    ): Promise<BrowserOperation> =>
      command(
        "signDocument",
        operationId,
        base64(utf8(JSON.stringify(documentRequest))),
      ),
    signAction: async (action: AppAction): Promise<BrowserOperation> => {
      validateAppAction(action);
      ensure(
        action.app_id === options.appId && action.origin === origin,
        "REQUEST_BINDING",
      );
      return command(
        "signAction",
        hex(action.operation_id),
        base64(canonical(action)),
      );
    },
    checkout: async (request: CheckoutRequest): Promise<BrowserOperation> => {
      validateShape("CheckoutRequest", request);
      ensure(request.offer.app_id === options.appId, "REQUEST_BINDING");
      return command(
        "checkout",
        hex(request.offer.operation_id),
        base64(canonical(request)),
      );
    },
    getOperation: (id: string) => command("getOperation", id),
    openOperation: (id: string) => command("openOperation", id),
    cancelOperation: (id: string) => command("cancelOperation", id),
    acknowledge: (id: string, resultDigest: string) =>
      command("acknowledge", id, null, resultDigest),
    disconnect: () => {
      port.disconnect();
      close();
    },
  };
}
