from pathlib import Path
import re,json,argparse
parser=argparse.ArgumentParser(description="Generate the exact public SDK shapes and CDDL")
parser.add_argument('--check', action='store_true')
check=parser.parse_args().check
def emit(path, content):
    if check:
        if not path.exists() or path.read_text()!=content: raise SystemExit(f'Stale generated contract: {path}')
    else: path.write_text(content)
root=Path(__file__).resolve().parents[1]
stage=root/'packages/dmsg-sdk/src'
rust=(root/'src/dmsg_types/src/integration.rs').read_text()
scalars={'u16':'bigint','u64':'bigint','u128':'bigint','bool':'boolean','String':'string','Principal':'Uint8Array','Hash':'Uint8Array','AccountId':'Uint8Array'}
def ty(x):
    if x.startswith('Vec<'): return ty(x[4:-1])+'[]'
    return scalars.get(x,x)
out=['// Generated from dmsg_types/src/integration.rs by generate-integration-sdk.py.\n// CBOR values use raw principal/hash/account bytes and bigint integers.\n',
     "export type Environment = 'Local' | 'Staging' | 'Production'\n",
     'export interface Account { owner: Uint8Array; subaccount: Uint8Array | null }\n',
     'export interface Beneficiary { product_id: string; authority_canister: Uint8Array; subject_schema: string; subject_bytes: Uint8Array }\n']
schemas={'Account':{'owner':'Principal','subaccount':'Option<Hash>'},'Beneficiary':{'product_id':'String','authority_canister':'Principal','subject_schema':'String','subject_bytes':'Bytes'},'Environment':['Local','Staging','Production']}
for kind,name,body in re.findall(r'pub (struct|enum) (\w+) \{(.*?)\n\}',rust,re.S):
    body=re.sub(r'^\s*///.*$|^\s*#\[.*$','',body,flags=re.M)
    if kind=='struct':
        fields=dict(re.findall(r'pub (\w+): ([\w<>]+),',body))
        schemas[name]=fields
        out.append('export interface '+name+' {\n'+''.join(f'  {k}: {ty(v)}\n' for k,v in fields.items())+'}\n')
    else:
        variants=[]; shape=[]
        for m in re.finditer(r'(\w+)\s*(?:\{([^}]+)\})?\s*,',body):
            tag,content=m.groups()
            if content:
                fields=dict(re.findall(r'(\w+): ([\w<>]+),',content))
                variants.append('{ '+tag+': { '+ '; '.join(f'{k}: {ty(v)}' for k,v in fields.items())+' } }')
                shape.append({tag:fields})
            else: variants.append(repr(tag)); shape.append(tag)
        schemas[name]=shape
        out.append('export type '+name+' =\n  | '+'\n  | '.join(variants)+'\n')
emit(stage/'contracts.ts', '\n'.join(out))
emit(stage/'schemas.ts', '// Generated exact wire schemas; unknown fields are rejected.\nexport const schemas = '+json.dumps(schemas,indent=2)+' as const\n')

# CDDL mirrors the exact closed records; semantic validators add admission rules.
def cddl_type(value):
    if value.startswith('Vec<'): return '[* ' + cddl_type(value[4:-1]) + ']'
    if value.startswith('Option<'): return '(' + cddl_type(value[7:-1]) + ' / null)'
    return value
lines=['; Generated by scripts/generate-integration-sdk.py. Canonical rules: integration.md.',
'u16 = 0..65535', 'u64 = 0..18446744073709551615',
'u128 = u64 / #6.2(bstr .size (9..16))', 'String = tstr', 'Principal = bstr .size (0..29)',
'Hash = bstr .size 32', 'AccountId = bstr .size 12', 'Bytes = bstr .size (0..64)']
for name,shape in schemas.items():
    if isinstance(shape,dict):
        lines.append(name+' = {\n'+''.join('  "'+k+'": '+cddl_type(v)+',\n' for k,v in shape.items())+'}')
    else:
        variants=[]
        for variant in shape:
            if isinstance(variant,str): variants.append('"'+variant+'"')
            else:
                for tag, fields in variant.items():
                    variants.append('{ "'+tag+'": { '+', '.join('"'+k+'": '+cddl_type(v) for k,v in fields.items())+' } }')
        lines.append(name+' = '+' / '.join(variants))
emit(root/'docs/protocol/integration.cddl', '\n\n'.join(lines)+'\n')
