# Load the environment variables
source "$(pwd)"/proposals/env.sh

quill sns make-proposal --canister-ids-file ./sns_canister_ids.json --pem-file $PROPOSAL_PEM_FILE $PROPOSAL_NEURON_ID --proposal '(
    record {
        title = "Add liquidity to PANDA/ICP pool on ICPSwap";
        url = "https://dashboard.internetcomputer.org/sns/d7wvo-iiaaa-aaaaq-aacsq-cai/proposal/6";
        summary = "We (the ICPanda DAO dev team) propose to add liquidity to the PANDA/ICP pool on ICPSwap. Following this motion proposal we will submit 2 additional proposals to transfer 6,000 ICP and 42,000,000 PANDA respectively to the PANDA/ICP swap pool canister owned by ICPSwap (5fq4w-lyaaa-aaaag-qjqta-cai).";
        action = opt variant {
            Motion = record {
                motion_text = "We (the ICPanda DAO dev team) propose to add liquidity to the PANDA/ICP pool on ICPSwap. Following this motion proposal we will submit 2 additional proposals to transfer 6,000 ICP and 42,000,000 PANDA respectively to the PANDA/ICP Swap pool canister owned by ICPSwap (5fq4w-lyaaa-aaaag-qjqta-cai).\n\nThe destination account for both transfers will be the same but on 2 different ledgers(ICP and PANDA) and is as follows:\nPrincipal: 5fq4w-lyaaa-aaaag-qjqta-cai\n\nSubaccount: [10,0,0,0,0,2,0,0,166,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] (this is the Subaccount generated from the ICPanda DAO governance canister Id, dwv6s-6aaaa-aaaaq-aacta-cai)\n\nThe liquidity funds are located in the Subaccount generated by the ICPanda DAO governance.\n\nSimultaneously, [@ICPSwap](https://twitter.com/ICPSwap) will tweet to verify that these proposals are correct and that they were initiated by the ICPSwap team.\n\nIf these proposals are approved, ICPSwap will add the funds to the liquidity pool. Half of the transferred funds will provide liquidity in the range of 6750 to 12000 ICP per PANDA, and the other half will provide liquidity in the full range for the ICP/PANDA pool.\n\nPlease note: There may be price fluctuations for PANDA between proposal initiation and successful transfer. When adding liquidity, the price range will be dynamically adjusted based on the current price of PANDA, but it will not deviate significantly from the set price range.\n\nSubsequent proposals can be made to add more liquidity or adjust the ranges if the price of PANDA experiences significant changes.\n";
            }
        };
    }
)' > proposal-message.json

# quill send proposal-message.json